services:
  db:
    image: postgres:15
    container_name: carshop_postgres_db
    environment:
      POSTGRES_USER: mycarshop
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
