version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret1
      POSTGRES_DB: carshop2
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: next@carshop.com
      PGADMIN_DEFAULT_PASSWORD: secret1
    ports:
      - "8070:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  db-network: